### ISSUE TITLE
expect mode cannot be enabled when dev mode is enabled

### ISSUE THREAD

**Issue by akd31** [hashicorp/docker-consul#62] opened 2017-07-11 07:53 UTC
I am trying to run consul on openshift container platform. I am using official consul docker image. I use CONSUL_LOCAL_CONFIG environment variable to get a 3 node consul cluster. 

My json file like this :  {
  "data_dir": "/var/consul",
  "log_level": "INFO",
  "node_name": "node1",
  "server": true,
  "ui": true,
  "bootstrap_expect": 3
}

I got an error like " Expect mode cannot be enabled when dev mode is enabled". How can I disable dev mode via using CONSUL_LOCAL_CONFIG variable?

**Comment by slackpad** [comment] 2017-07-18 16:30
Duplicate of https://github.com/hashicorp/consul/issues/3255.

**Closed by slackpad** 2017-07-18 16:30 UTC
